#!/usr/bin/expect -f

set timeout -1

spawn telnet 192.168.1.232

expect "Password: "

send "B3ckf3r3!@#\r"

send "enable\r"

expect "Password: "

send "B3CKF3R3!@#\r"

send "copy running-config tftp://192.168.1.113//8c3082fa-d091-4916-9db4-61f3f78fdf28-1665062087\r"

expect "Address or name of remote host []?"

send "192.168.1.113\r"

expect "Destination filename ?"

send "\r"
send "exit\r"